language: java

sudo: false

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6

install: true

script: ./mvnw verify -Ppitest

after_success:
  - ./mvnw coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'
